# Generated by Django 5.2.4 on 2025-12-04 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("film", "0001_initial"),
        ("planet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("birth_year", models.CharField(blank=True, max_length=50)),
                ("gender", models.CharField(blank=True, max_length=50)),
                ("height", models.CharField(blank=True, max_length=50)),
                ("mass", models.CharField(blank=True, max_length=50)),
                (
                    "films",
                    models.ManyToManyField(
                        blank=True, related_name="characters", to="film.film"
                    ),
                ),
                (
                    "homeworld",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="residents",
                        to="planet.planet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
