# Generated by Django 5.2.4 on 2025-12-04 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("planet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("episode_id", models.IntegerField(blank=True, null=True)),
                ("opening_crawl", models.TextField(blank=True)),
                ("director", models.CharField(blank=True, max_length=200)),
                ("producers", models.CharField(blank=True, max_length=300)),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "planets",
                    models.ManyToManyField(
                        blank=True, related_name="films", to="planet.planet"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
